# Generated by Django 5.2.12 on 2026-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_country_user_date_verified_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, choices=[('NIN', 'NIN'), ('PASSPORT', 'Passport'), ('DRIVERS', "Driver's License"), ('VOTER', "Voter's Card"), ('NATIONAL_ID', 'National ID')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('MICRO', 'Micro-Investor'), ('SALARY', 'Salary Earner'), ('BUSINESS', 'Business Owner / HNI'), ('REFERRAL', 'Referral Builder'), ('DIASPORA', 'Diaspora Nigerian')], default='MICRO', max_length=20),
        ),
    ]
