# Generated by Django 5.2.12 on 2026-05-27 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_id_number_user_id_type_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAPIConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exchange', models.CharField(choices=[('BINANCE', 'Binance'), ('BYBIT', 'Bybit')], max_length=20)),
                ('api_key', models.TextField()),
                ('api_secret', models.TextField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
