# Generated by Django 5.2.12 on 2026-05-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_exchangeapiconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeapiconnection',
            name='fee_per_trade',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=10),
        ),
        migrations.AddField(
            model_name='exchangeapiconnection',
            name='min_capital',
            field=models.DecimalField(decimal_places=8, default=1000, max_digits=20),
        ),
        migrations.AlterField(
            model_name='exchangeapiconnection',
            name='exchange',
            field=models.CharField(choices=[('BINANCE', 'Binance'), ('BYBIT', 'Bybit'), ('OKX', 'OKX'), ('KUCOIN', 'KuCoin'), ('GATEIO', 'Gate.io'), ('MEXC', 'MEXC'), ('BITGET', 'Bitget')], max_length=20),
        ),
    ]
