# Generated by Django 5.2.12 on 2026-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_exchangeapiconnection_fee_per_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeapiconnection',
            name='aum_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='exchangeapiconnection',
            name='fee_last_charged',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangeapiconnection',
            name='grids_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangeapiconnection',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='exchangeapiconnection',
            name='warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
