# Generated by Django 5.2.12 on 2026-06-01 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_exchangeapiconnection_aum_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('destination_wallet', models.CharField(max_length=42)),
                ('direction', models.CharField(choices=[('BUY', 'Buy Crypto (Naira → Crypto)'), ('SELL', 'Sell Crypto (Crypto → Naira)')], max_length=4)),
                ('pin_hash', models.CharField(max_length=64)),
                ('pin_expiry', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]