# Generated by Django 5.2.12 on 2026-06-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_profile_caption_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_caption',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]