# Generated by Django 5.2.12 on 2026-06-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_profile_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_caption',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]