# Generated by Django 5.2.12 on 2026-09-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_profile_caption_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeapiconnection',
            name='fee_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangeapiconnection',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangeapiconnection',
            name='withdrawal_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
