# Generated by Django 5.2.12 on 2026-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_exchangeapiconnection_fee_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeapiconnection',
            name='api_passphrase',
            field=models.TextField(blank=True, default=''),
        ),
    ]
