services:
  - type: web
    name: node-volatility-crypto
    runtime: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0