# Generated by Django 5.2.12 on 2026-05-03 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0004_add_initial_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GridBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('lower_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('upper_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('grids', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10)),
                ('grid_profit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.cryptotoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
