# Generated by Django 5.2.12 on 2026-05-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridbot',
            name='price_at_creation',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gridbot',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
