# Generated by Django 5.2.12 on 2026-05-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_gridbot_price_at_creation_gridbot_stopped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridbot',
            name='total_yield_earned',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
