# Generated by Django 5.2.12 on 2026-05-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_remove_gridbot_updated_at_gridbot_auto_closed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridbot',
            name='auto_closed_at',
        ),
        migrations.AddField(
            model_name='gridbot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
