# Generated by Django 5.2.12 on 2026-05-21 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_purchase_order_type'),
        ('trading', '0003_gridbot_total_yield_earned'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGridBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('lower_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('upper_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('grids', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10)),
                ('grid_profit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('price_at_creation', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokens.cryptotoken')),
            ],
        ),
    ]
