# Generated by Django 5.2.12 on 2026-05-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_mastergridbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridbot',
            name='pnl',
            field=models.DecimalField(max_digits=20, decimal_places=8, default=0),
        ),
        migrations.AddField(
            model_name='gridbot',
            name='pnl_percent',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0),
        ),
    ]