# Generated by Django 5.2.12 on 2026-05-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_add_pnl_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridbot',
            name='fee_reserve',
            field=models.DecimalField(max_digits=20, decimal_places=8, default=0),
        ),
        migrations.AddField(
            model_name='gridbot',
            name='referrer_reserve',
            field=models.DecimalField(max_digits=20, decimal_places=8, default=0),
        ),
    ]