# Generated by Django 5.2.12 on 2026-08-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_remove_gridbot_fee_reserve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridbot',
            name='is_savings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gridbot',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
