# Generated by Django 5.2.12 on 2026-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_gridbot_is_savings_gridbot_lock_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
