# Generated by Django 5.2.12 on 2026-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_cashflowsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridbot',
            name='is_above_fair_value',
            field=models.BooleanField(default=False),
        ),
    ]
