# Generated by Django 5.2.12 on 2026-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_gridbot_is_above_fair_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridbot',
            name='near_close_notified',
            field=models.BooleanField(default=False),
        ),
    ]
