# Generated by Django 5.2.12 on 2026-09-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_gridbot_near_close_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridbot',
            name='last_yield_credited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
