# Generated by Django 5.2.12 on 2026-09-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_gridbot_last_yield_credited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridbot',
            name='grid_profit_snapshot',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='gridbot',
            name='grid_profit_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gridbot',
            name='grid_profit_yesterday',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
