# Generated by Django 5.2.12 on 2026-08-02 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_account', models.CharField(max_length=20)),
                ('api_key_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_mt5_account', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=4)),
                ('volume', models.FloatField()),
                ('open_price', models.FloatField()),
                ('open_time', models.DateTimeField()),
                ('ticket', models.BigIntegerField()),
                ('magic_number', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlaveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_account', models.CharField(max_length=20)),
                ('mt5_password_encrypted', models.TextField()),
                ('broker_server', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlaveTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slave_ticket', models.BigIntegerField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave_trades', to='forex_ea.mastertrade')),
                ('slave_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex_ea.slaveaccount')),
            ],
        ),
    ]
