# Generated by Django 5.2.12 on 2026-08-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0002_masteraccount_mastertrade_slaveaccount_slavetrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(default='forex', max_length=20)),
                ('weather', models.CharField(default='Sunny', max_length=50)),
                ('trend', models.CharField(default='NEUTRAL', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
