# Generated by Django 5.2.12 on 2026-08-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0003_marketweather'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('forex', 'Forex'), ('crypto', 'Crypto'), ('stock', 'Stock'), ('economic', 'Economic')], max_length=20)),
                ('caption', models.CharField(max_length=100)),
                ('trend', models.CharField(choices=[('UPTREND', 'Uptrend'), ('DOWNTREND', 'Downtrend'), ('CONSOLIDATION', 'Consolidation')], default='CONSOLIDATION', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('symbol', 'created_at')},
            },
        ),
    ]
