# Generated by Django 5.2.12 on 2026-08-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0005_coinreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyintelligence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
