# Generated by Django 5.2.12 on 2026-08-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0006_alter_dailyintelligence_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=5, max_digits=15)),
                ('high', models.DecimalField(decimal_places=5, max_digits=15)),
                ('low', models.DecimalField(decimal_places=5, max_digits=15)),
                ('close', models.DecimalField(decimal_places=5, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
