# Generated by Django 5.2.12 on 2026-08-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0007_forexcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('current_price', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('trend', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=30)),
                ('trigger', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
