# Generated by Django 5.2.12 on 2026-08-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0008_forexforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexforecast',
            name='daily_candle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
