# Generated by Django 5.2.12 on 2026-08-18 10:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0009_forexforecast_daily_candle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexforecast',
            name='condition',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='forexforecast',
            name='trend',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='forexforecast',
            name='trigger',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='FiatBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira'), ('GOLD', 'Gold (XAU)'), ('USOIL', 'US Oil (WTI)')], max_length=6)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiat_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fiat balances',
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
