# Generated by Django 5.2.12 on 2026-08-20 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0010_alter_forexforecast_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiatbalance',
            options={'verbose_name_plural': 'Spot balances'},
        ),
        migrations.AlterField(
            model_name='fiatbalance',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira'), ('GOLD', 'Gold (XAU)'), ('USOIL', 'US Oil (WTI)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='fiatbalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_balances', to=settings.AUTH_USER_MODEL),
        ),
    ]
