# Generated by Django 5.2.12 on 2026-08-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0012_stockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
