# Generated by Django 5.2.12 on 2026-08-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0013_stockpricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
