# Generated by Django 5.2.12 on 2026-09-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_ea', '0015_stockorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexratehistory',
            name='buy_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='forexratehistory',
            name='sell_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='forexratehistory',
            name='source',
            field=models.CharField(default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='forexratehistory',
            name='source_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
