# Generated by Django 5.2.12 on 2026-03-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_takeprofitorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokenbalance',
            name='highest_price_since_purchase',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='usertokenbalance',
            name='take_profit_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TakeProfitOrder',
        ),
    ]
