# Generated by Django 5.2.12 on 2026-03-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_usertokenbalance_highest_price_since_purchase_and_more'),
    ]

    operations = [
    ]
