# Generated by Django 5.2.12 on 2026-05-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_add_initial_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'Market Order'), ('GRID', 'Grid Bot')], default='MARKET', max_length=10),
        ),
    ]
