# Generated by Django 5.2.12 on 2026-05-24 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_purchase_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_end', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_closes', to='tokens.cryptotoken')),
            ],
            options={
                'ordering': ['week_end'],
                'unique_together': {('token', 'week_end')},
            },
        ),
    ]
