# Generated by Django 5.2.12 on 2026-06-06 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_weeklyclose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NODEToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pending_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_earned', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('source', models.CharField(choices=[('TRACKER', 'Position Tracker Activation'), ('KYC', 'KYC Verification'), ('REFERRAL', 'Referral Bonus'), ('PROMO', 'Promo Code'), ('STREAK', 'Streak Bonus'), ('ADMIN', 'Admin Airdrop'), ('CONVERSION', 'Converted to USDC'), ('EXPIRY', 'Expired/Burned')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACTIVATED', 'Activated'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted to USDC')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
