# Generated by Django 5.2.12 on 2026-05-17 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_depositrequest_withdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='lock_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pension_fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pension_reinvest_months',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pension_reinvest_years',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Purse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('auto_sweep_enabled', models.BooleanField(default=False)),
                ('sweep_percentage', models.IntegerField(default=10)),
                ('sweep_schedule', models.CharField(default='weekly', max_length=20)),
                ('withdraw_schedule', models.CharField(default='anytime', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
