# Generated by Django 5.2.12 on 2026-09-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_wallet_lock_enabled_wallet_locked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('YIELD', 'Yield'), ('REFERRAL', 'Referral'), ('PENALTY', 'Early Exit Penalty')], max_length=20),
        ),
    ]
