# Generated by Django 4.2 on 2026-03-25 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('distribution_number', models.IntegerField()),
                ('month_year', models.CharField(max_length=7)),
                ('is_credited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('token_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_distributions', to='tokens.usertokenbalance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
