# Generated by Django 5.2.12 on 2026-04-29 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_transparencychatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transparencychatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='transparencychatmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chat.transparencychatmessage'),
        ),
    ]
