# Generated by Django 5.2.12 on 2026-08-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_transparencychatmessage_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencychatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/'),
        ),
    ]
